CREATE TABLE abstract_users (
    user_id uuid NOT NULL default gen_random_uuid (),
    name character varying NOT NULL,
    surname character varying NOT NULL,
    CONSTRAINT abstract_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE user_settings (
    user_id uuid NOT NULL,
    theme character varying NOT NULL default 'light' :: character varying,
    language character varying NOT NULL default 'EN' :: character varying,
    CONSTRAINT user_settings_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NULL,
    description character varying NULL,
    CONSTRAINT logs_pkey PRIMARY KEY (log_id),
    CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE
    SET
        NULL
);

CREATE TABLE courier_users (
    user_id uuid NOT NULL,
    rating smallint NOT NULL,
    CONSTRAINT courier_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT courier_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE admin_users (
    user_id uuid NOT NULL,
    role character varying NOT NULL,
    CONSTRAINT admin_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id)
);

CREATE TABLE news (
    news_id uuid NOT NULL default gen_random_uuid (),
    title character varying NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    posted_by uuid NULL,
    CONSTRAINT news_pkey PRIMARY KEY (news_id),
    CONSTRAINT news_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES admin_users (user_id) ON UPDATE CASCADE ON DELETE
    SET
        NULL
);

CREATE TABLE advertisement_banners (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    author uuid NULL,
    date_created date NOT NULL,
    showing_term date NOT NULL,
    banner_link character varying NOT NULL,
    CONSTRAINT advertisement_banners_pkey PRIMARY KEY (id),
    CONSTRAINT advertisement_banners_author_fkey FOREIGN KEY (author) REFERENCES admin_users (user_id) ON UPDATE CASCADE ON DELETE
    SET
        NULL
);

CREATE TABLE client_users (
    user_id uuid NOT NULL,
    registered_from date NOT NULL,
    CONSTRAINT client_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT client_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE shops (
    shop_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    official_organization_name character varying NOT NULL,
    registration_number character varying NOT NULL,
    description text NOT NULL,
    CONSTRAINT shop_pkey PRIMARY KEY (shop_id)
);

CREATE TABLE shop_pick_up_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    address character varying NOT NULL,
    shop_id integer NOT NULL,
    operating_mode character varying NOT NULL,
    CONSTRAINT shop_pick_up_points_pkey PRIMARY KEY (id),
    CONSTRAINT shop_pick_up_points_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE shop_representative_users (
    user_id uuid NOT NULL,
    shop_id integer NOT NULL,
    CONSTRAINT shop_representative_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT shop_representative_users_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shop_representative_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE shipping_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description character varying NOT NULL,
    CONSTRAINT shipping_methods_pkey PRIMARY KEY (id)
);

CREATE TABLE shop_shipping_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    shipping_method smallint NOT NULL,
    shop integer NOT NULL,
    CONSTRAINT shop_shipping_methods_pkey PRIMARY KEY (id),
    CONSTRAINT shop_shipping_methods_shipping_method_fkey FOREIGN KEY (shipping_method) REFERENCES shipping_methods (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shop_shipping_methods_shop_fkey FOREIGN KEY (shop) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE payment_approaches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description character varying NOT NULL,
    CONSTRAINT payment_approaches_pkey PRIMARY KEY (id)
);

CREATE TABLE shop_payment_approaches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    shop integer NOT NULL,
    payment_approach bigint NOT NULL,
    CONSTRAINT shop_payment_approaches_pkey PRIMARY KEY (id),
    CONSTRAINT shop_payment_approaches_payment_approach_fkey FOREIGN KEY (payment_approach) REFERENCES payment_approaches (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shop_payment_approaches_shop_fkey FOREIGN KEY (shop) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE forums (
    forum_id bigint GENERATED BY DEFAULT AS IDENTITY,
    topic character varying NOT NULL,
    description text NULL,
    CONSTRAINT forums_pkey PRIMARY KEY (forum_id)
);

CREATE TABLE forum_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    forum_id bigint NOT NULL,
    author uuid NOT NULL,
    date timestamp without time zone NOT NULL,
    text text NOT NULL,
    CONSTRAINT forum_comments_pkey PRIMARY KEY (id),
    CONSTRAINT forum_comments_author_fkey FOREIGN KEY (author) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT forum_comments_forum_id_fkey FOREIGN KEY (forum_id) REFERENCES forums (forum_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE coupons (
    coupon_id integer GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    description character varying NOT NULL,
    sale_amount smallint NOT NULL,
    validity_period date NOT NULL,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id)
);

CREATE TABLE frequently_asked_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    question character varying NOT NULL,
    answer text NOT NULL,
    CONSTRAINT frequently_asked_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE categories (
    category_id smallint GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE subcategories (
    subcategory_id integer GENERATED BY DEFAULT AS IDENTITY,
    parent_category smallint NOT NULL,
    title character varying NOT NULL,
    CONSTRAINT subcategories_pkey PRIMARY KEY (subcategory_id),
    CONSTRAINT subcategories_parent_category_fkey FOREIGN KEY (parent_category) REFERENCES categories (category_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE manufacturers (
    manufacturer_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    info text NULL,
    CONSTRAINT manufacturers_pkey PRIMARY KEY (manufacturer_id)
);

CREATE TABLE model_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    manufacturer integer NOT NULL,
    name character varying NULL,
    info text NOT NULL,
    CONSTRAINT model_lines_pkey PRIMARY KEY (id),
    CONSTRAINT model_lines_manufacturer_fkey FOREIGN KEY (manufacturer) REFERENCES manufacturers (manufacturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    title character varying NOT NULL,
    subcategory integer NULL,
    model_line bigint NULL,
    description text NOT NULL,
    CONSTRAINT items_pkey PRIMARY KEY (item_id),
    CONSTRAINT items_model_line_fkey FOREIGN KEY (model_line) REFERENCES model_lines (id) ON UPDATE CASCADE ON DELETE
    SET NULL,
    CONSTRAINT items_subcategory_fkey FOREIGN KEY (subcategory) REFERENCES subcategories (subcategory_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE priced_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    price real NOT NULL,
    shop integer NOT NULL,
    item bigint NOT NULL,
    CONSTRAINT priced_items_pkey PRIMARY KEY (id),
    CONSTRAINT priced_items_item_fkey FOREIGN KEY (item) REFERENCES items (item_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT priced_items_shop_fkey FOREIGN KEY (shop) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date timestamp with time zone NOT NULL default now(),
    shop integer NULL,
    client uuid NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_client_fkey FOREIGN KEY (client) REFERENCES client_users (user_id) ON UPDATE CASCADE ON DELETE
    SET NULL,
    CONSTRAINT orders_shop_fkey FOREIGN KEY (shop) REFERENCES shops (shop_id) ON UPDATE CASCADE ON DELETE
    SET NULL
);

CREATE TABLE ordered_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "order" bigint NOT NULL,
    item bigint NOT NULL,
    fixed_price real NOT NULL,
    items_count smallint NOT NULL,
    CONSTRAINT ordered_items_pkey PRIMARY KEY (id),
    CONSTRAINT ordered_items_item_fkey FOREIGN KEY (item) REFERENCES items (item_id) ON UPDATE CASCADE ON DELETE
    SET NULL,
    CONSTRAINT ordered_items_order_fkey FOREIGN KEY ("order") REFERENCES orders (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reviews (
    review_id bigint GENERATED BY DEFAULT AS IDENTITY,
    text text NOT NULL,
    item bigint NOT NULL,
    author uuid NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
    CONSTRAINT reviews_author_fkey FOREIGN KEY (author) REFERENCES client_users (user_id) ON UPDATE CASCADE ON DELETE
    SET NULL,
    CONSTRAINT reviews_item_fkey FOREIGN KEY (item) REFERENCES items (item_id) ON UPDATE CASCADE ON DELETE CASCADE
);