CREATE TABLE abstract_users (
    user_id uuid NOT NULL default gen_random_uuid (),
    name character varying NOT NULL,
    surname character varying NOT NULL,
    CONSTRAINT abstract_users_pkey PRIMARY KEY (user_id)
) tablespace pg_default;

CREATE TABLE user_settings (
    user_id uuid NOT NULL,
    theme character varying NOT NULL default 'light' :: character varying,
    language character varying NOT NULL default 'EN' :: character varying,
    CONSTRAINT user_settings_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid null,
    description character varying null,
    CONSTRAINT logs_pkey PRIMARY KEY (log_id),
    CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
) tablespace pg_default;

CREATE TABLE courier_users (
    user_id uuid NOT NULL,
    rating smallint NOT NULL,
    CONSTRAINT courier_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT courier_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE admin_users (
    user_id uuid NOT NULL,
    role character varying NOT NULL,
    CONSTRAINT admin_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id)
) tablespace pg_default;

CREATE TABLE news (
    news_id uuid NOT NULL default gen_random_uuid (),
    title character varying NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    posted_by uuid null,
    CONSTRAINT news_pkey PRIMARY KEY (news_id),
    CONSTRAINT news_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES admin_users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
) tablespace pg_default;

CREATE TABLE advertisement_banners (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    author uuid null,
    date_created date NOT NULL,
    showing_term date NOT NULL,
    banner_link character varying NOT NULL,
    CONSTRAINT advertisement_banners_pkey PRIMARY KEY (id),
    CONSTRAINT advertisement_banners_author_fkey FOREIGN KEY (author) REFERENCES admin_users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
) tablespace pg_default;

CREATE TABLE client_users (
    user_id uuid NOT NULL,
    registered_from date NOT NULL,
    CONSTRAINT client_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT client_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE shop (
    shop_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    official_organization_name character varying NOT NULL,
    registration_number character varying NOT NULL,
    description text NOT NULL,
    CONSTRAINT shop_pkey PRIMARY KEY (shop_id)
) tablespace pg_default;

CREATE TABLE shop_pick_up_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    address character varying NOT NULL,
    shop_id integer NOT NULL,
    operating_mode character varying NOT NULL,
    CONSTRAINT shop_pick_up_points_pkey PRIMARY KEY (id),
    CONSTRAINT shop_pick_up_points_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE shop_representative_users (
    user_id uuid NOT NULL,
    shop_id integer NOT NULL,
    CONSTRAINT shop_representative_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT shop_representative_users_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (shop_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shop_representative_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES abstract_users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE shipping_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description character varying NOT NULL,
    CONSTRAINT shipping_methods_pkey PRIMARY KEY (id)
) tablespace pg_default;

CREATE TABLE shop_shipping_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    shipping_method smallint NOT NULL,
    shop integer NOT NULL,
    CONSTRAINT shop_shipping_methods_pkey PRIMARY KEY (id),
    CONSTRAINT shop_shipping_methods_shipping_method_fkey FOREIGN KEY (shipping_method) REFERENCES shipping_methods (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shop_shipping_methods_shop_fkey FOREIGN KEY (shop) REFERENCES shop (shop_id) ON UPDATE CASCADE ON DELETE CASCADE
) tablespace pg_default;

CREATE TABLE
  payment_approaches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    description character varying NOT NULL,
    CONSTRAINT payment_approaches_pkey PRIMARY KEY (id)
  ) tablespace pg_default;