# Generated by Django 4.0.4 on 2022-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0003_movietheater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietheater',
            old_name='link_to_google_maps_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='movietheater',
            name='photo',
            field=models.CharField(default='photo', max_length=600),
        ),
    ]
