# Generated by Django 4.0.4 on 2022-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0004_rename_link_to_google_maps_location_movietheater_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietheater',
            name='visits_count',
            field=models.IntegerField(default=0),
        ),
    ]
