# Generated by Django 4.0.4 on 2022-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0006_movietheater_theaters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietheater',
            old_name='theaters',
            new_name='movies',
        ),
    ]
