# Generated by Django 4.0.4 on 2022-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0007_rename_theaters_movietheater_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinematicUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
