# Generated by Django 4.0.4 on 2022-05-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0008_cinematicuniverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marveldcmovies.cinematicuniverse'),
        ),
    ]
