# Generated by Django 4.0.4 on 2022-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0009_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietheater',
            name='telephone',
            field=models.CharField(default='+375', max_length=80),
        ),
    ]
