# Generated by Django 4.0.4 on 2022-05-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marveldcmovies', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
