name: Build React-App and deploy to Surge

on:
  push:
    paths:
      - 2\ year\ -\ Movie\ Ticket\ Sales\ Service/**
    

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      # Install node version 16.2.0
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16.2.0'

    - name: Install dependencies
      run: |
        cd 2\ year\ -\ Movie\ Ticket\ Sales\ Service/
        cd client
        npm install
        npm install surge

    - name: Build
      run: |
        cd 2\ year\ -\ Movie\ Ticket\ Sales\ Service/
        cd client  
        npm run build

    - name: Deploy
      run: |
        cd 2\ year\ -\ Movie\ Ticket\ Sales\ Service/
        cd client
        cd build 
        npm install surge
        npx surge ./ ${{secrets.SURGE_URL_FOR_MOVIES_SERVICE}} --token ${{secrets.SURGE_TOKEN}}