name: Build React-App and deploy to Surge

on: [push]
    

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      # Install node version 16.2.0
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '16.2.0'

    - name: move to folder
      run: |
        cd 2\ year\ -\ Movie\ Ticket\ Sales\ Service/
        cd client

    - name: Install dependencies
      run: |
        npm install
        npm install surge

    - name: Build
      run: |  
        npm run build
        cd build

    - name: Deploy
      run: | 
        surge . ${{secrets.SURGE_URL_FOR_MOVIES_SERVICE}} --token ${{secrets.SURGE_TOKEN}}